import { useEffect, useRef, useState } from 'react'
import type { CSSProperties } from 'react'
import './AgentAssistant.css'
import './AgentVoice.css'

type ForecastContext={PSGC:string;BARANGAY:string;MUNICIPALITY:string}|null
type Evidence={source?:string;DATE?:string;PSGC?:string;BARANGAY?:string;MUNICIPALITY?:string;POSTERIOR_MEAN_CASES?:number;OUTBREAK_PROBABILITY?:number;ALERT_LEVEL?:string;facts?:string}
type AgentResponse={answer:string;evidence:Evidence[];warnings:string[];actions:{date?:string;psgc?:string;openDetail?:boolean;page?:'methodology'}}

export default function AgentAssistant({date,selected,onNavigate}:{date?:string;selected:ForecastContext;onNavigate:(actions:AgentResponse['actions'])=>void}){
  const [open,setOpen]=useState(false),[message,setMessage]=useState(''),[response,setResponse]=useState<AgentResponse|null>(null),[displayedAnswer,setDisplayedAnswer]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[recording,setRecording]=useState(false),[transcribing,setTranscribing]=useState(false),[speaking,setSpeaking]=useState(false),[voiceLevel,setVoiceLevel]=useState(0)
  const inputRef=useRef<HTMLInputElement>(null),requestRef=useRef<AbortController|null>(null),recorderRef=useRef<MediaRecorder|null>(null),audioRef=useRef<HTMLAudioElement|null>(null),audioUrlRef=useRef(''),recordingTimerRef=useRef<number>(0),animationRef=useRef<number>(0),audioContextRef=useRef<AudioContext|null>(null),spokenResponseRef=useRef<AgentResponse|null>(null)
  useEffect(()=>{if(open)inputRef.current?.focus()},[open])
  useEffect(()=>{setDisplayedAnswer('');if(!response?.answer)return;let index=0;const timer=window.setInterval(()=>{index=Math.min(index+3,response.answer.length);setDisplayedAnswer(response.answer.slice(0,index));if(index===response.answer.length)clearInterval(timer)},18);return()=>clearInterval(timer)},[response])
  useEffect(()=>()=>{requestRef.current?.abort();recorderRef.current?.stream.getTracks().forEach(track=>track.stop());audioRef.current?.pause();URL.revokeObjectURL(audioUrlRef.current);clearTimeout(recordingTimerRef.current);cancelAnimationFrame(animationRef.current);void audioContextRef.current?.close()},[])
  const ask=async(text=message)=>{const question=text.trim();if(!question||loading)return;requestRef.current?.abort();const controller=new AbortController();requestRef.current=controller;setLoading(true);setResponse(null);setError('');try{const result=await fetch('/api/agent/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:question,context:{date,psgc:selected?.PSGC}}),signal:controller.signal});const data=await result.json();if(!result.ok)throw new Error(data.message??data.error??`Request failed (${result.status})`);setResponse(data);setMessage('')}catch(reason){if((reason as Error).name!=='AbortError')setError(reason instanceof Error?reason.message:'Assistant unavailable')}finally{if(requestRef.current===controller)setLoading(false)}}
  const toggleRecording=async()=>{if(recording){recorderRef.current?.stop();return}if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('Audio recording is unavailable in this browser.');return}setError('');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),chunks:Blob[]=[];const recorder=new MediaRecorder(stream),context=new AudioContext(),analyser=context.createAnalyser(),samples=new Uint8Array(analyser.frequencyBinCount);context.createMediaStreamSource(stream).connect(analyser);audioContextRef.current=context;const meter=()=>{analyser.getByteFrequencyData(samples);setVoiceLevel(samples.reduce((sum,value)=>sum+value,0)/samples.length/90);animationRef.current=requestAnimationFrame(meter)};meter();recorderRef.current=recorder;recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=async()=>{clearTimeout(recordingTimerRef.current);cancelAnimationFrame(animationRef.current);void context.close();setVoiceLevel(0);stream.getTracks().forEach(track=>track.stop());setRecording(false);setTranscribing(true);try{const audio=new Blob(chunks,{type:recorder.mimeType||'audio/webm'}),result=await fetch('/api/agent/transcribe',{method:'POST',headers:{'Content-Type':audio.type.split(';')[0]},body:audio}),data=await result.json();if(!result.ok)throw new Error(data.message??data.error??'Transcription failed');setMessage(data.text);setTranscribing(false);await ask(data.text)}catch(reason){setError(reason instanceof Error?reason.message:'Transcription failed');setTranscribing(false)}};recorder.start();recordingTimerRef.current=window.setTimeout(()=>recorder.stop(),60000);setRecording(true)}catch{setError('Microphone permission is required for voice input.')}}
  const speak=async()=>{if(speaking){audioRef.current?.pause();audioRef.current=null;URL.revokeObjectURL(audioUrlRef.current);audioUrlRef.current='';setSpeaking(false);return}if(!response)return;const summary=(response.answer.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.slice(0,2).join(' ')??response.answer).slice(0,600);setError('');setSpeaking(true);try{const result=await fetch('/api/agent/speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:summary})});if(!result.ok){const data=await result.json();throw new Error(data.message??data.error??'Speech generation failed')}const url=URL.createObjectURL(await result.blob()),audio=new Audio(url);audioUrlRef.current=url;audioRef.current=audio;const finish=()=>{URL.revokeObjectURL(url);audioUrlRef.current='';audioRef.current=null;setSpeaking(false)};audio.onended=finish;audio.onerror=()=>{finish();setError('Audio playback failed.')};await audio.play()}catch(reason){URL.revokeObjectURL(audioUrlRef.current);audioUrlRef.current='';audioRef.current=null;setSpeaking(false);setError(reason instanceof Error?reason.message:'Speech generation failed')}}
  useEffect(()=>{if(!response||spokenResponseRef.current===response)return;spokenResponseRef.current=response;void speak()},[response])
  return <>
    <button className="agent-launcher" aria-label="Open ORACLIS assistant" aria-expanded={open} onClick={()=>{if(open&&recording)recorderRef.current?.stop();setOpen(value=>!value)}}><span className="agent-launcher-orb">AI</span><span className="agent-launcher-label">{open?'Close':'Ask ORACLIS'}</span></button>
    {open&&<section className="agent-drawer" role="dialog" aria-modal="false" aria-labelledby="agent-title">
      <div className="agent-grid" aria-hidden="true"/><div className="agent-scan" aria-hidden="true"/>
      <header><div className="agent-identity"><span className="agent-core" aria-hidden="true"><i/></span><div><span className="eyebrow">Grounded intelligence</span><h2 id="agent-title">ORACLIS <em>AI</em></h2><span className="agent-online"><i/>Evidence link active</span></div></div><button className="agent-close" aria-label="Close assistant" onClick={()=>{if(recording)recorderRef.current?.stop();setOpen(false)}}>×</button></header>
      <div className="agent-context"><span>{date?.slice(0,7)??'No date'}</span><span>{selected?`${selected.BARANGAY} · ${selected.MUNICIPALITY}`:'No barangay selected'}</span></div>
      <div className="agent-suggestions">{['Explain this barangay','Current reported cases','Show highest-risk barangays','Explain the Bayesian model'].map(item=><button key={item} onClick={()=>void ask(item)} disabled={loading}>{item}</button>)}<button onClick={()=>{window.location.hash='/methodology'}}>Show formulas</button></div>
      {(recording||transcribing)&&<div className="agent-voice-float" role="status"><div className="agent-voice-orb" style={{'--voice-level':Math.min(voiceLevel,1)} as CSSProperties}>{[.7,1,.55,1.2,.8].map((scale,index)=><i key={index} style={{'--bar-scale':scale} as CSSProperties}/>)}</div><strong>{recording?'Listening':'Understanding your question'}</strong><span>{recording?'Tap stop when finished':'Sending to ORACLIS automatically…'}</span>{recording&&<button onClick={()=>recorderRef.current?.stop()}>Stop & send</button>}</div>}
      <div className="agent-answer" aria-live="polite">{loading?<div className="agent-thinking"><i/><span>Organizing grounded evidence…</span></div>:error?<p className="agent-error">{error}</p>:response?<><div className="agent-structured-answer">{displayedAnswer.match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.reduce<string[][]>((groups,sentence,index)=>{if(index%2===0)groups.push([]);groups.at(-1)?.push(sentence.trim());return groups},[]).map((group,index)=><p key={index}>{group.join(' ')}</p>)}{displayedAnswer.length<response.answer.length&&<i className="agent-caret"/>}</div><div className="agent-actions"><button className={`agent-map-action${speaking?' is-active':''}`} onClick={()=>void speak()}>{speaking?'Stop voice':'Voice summary'}</button>{response.actions.psgc&&<button className="agent-map-action" onClick={()=>onNavigate(response.actions)}>Show on map</button>}<a className="agent-map-action" href="#/methodology">Show formulas</a></div>{response.evidence.length>0&&<details><summary>Supporting data · {response.evidence.length}</summary>{response.evidence.map((item,index)=><article key={index}><strong>{item.BARANGAY?`${item.BARANGAY} · ${item.MUNICIPALITY}`:item.source??'Model implementation'}</strong>{item.POSTERIOR_MEAN_CASES!==undefined&&<span>{item.POSTERIOR_MEAN_CASES.toFixed(1)} projected cases · {Math.round((item.OUTBREAK_PROBABILITY??0)*100)}% probability · {item.ALERT_LEVEL}</span>}{item.facts&&<span>{item.facts}</span>}</article>)}</details>}{response.warnings.length>0&&<small>{response.warnings.join(' ')}</small>}</>:<div className="agent-empty"><strong>Ask about model outputs</strong><span>Risk, uncertainty, rankings, spatial pressure, or mathematics.</span></div>}</div>
      <form onSubmit={event=>{event.preventDefault();void ask()}}><button type="button" className={`agent-mic${recording?' is-recording':''}`} disabled={transcribing} onClick={()=>void toggleRecording()} aria-label={recording?'Stop recording':'Record question'}>{transcribing?'…':recording?'■':'●'}</button><input ref={inputRef} value={message} maxLength={1000} onChange={event=>setMessage(event.target.value)} placeholder={recording?'Listening…':transcribing?'Transcribing with Groq…':'Ask or record a question…'} aria-label="Question for ORACLIS assistant"/><button disabled={loading||recording||transcribing||!message.trim()} aria-label="Send question"><span>↑</span></button></form>
    </section>}
  </>
}
