import './MethodologyPage.css'

const weights=[['MLR','46.76%'],['XGBoost','21.76%'],['SARIMAX','16.01%'],['LSTM','15.47%']]
const metrics=[['R²','0.9521'],['RMSE','4.0615'],['MAE','1.9146'],['MAPE','5.5948%'],['WAPE','5.2448%'],['Test observations','216']]

export default function MethodologyPage(){return <main className="methodology-page">
  <header className="methodology-nav"><a className="methodology-brand" href="#/"><span>O</span><strong>ORACLIS</strong></a><a className="methodology-back" href="#/">← Return to dashboard</a></header>
  <section className="methodology-hero"><div><span className="methodology-kicker">Scientific reference · version 2026.07</span><h1>How ORACLIS turns history into <em>spatial risk scenarios</em></h1><p>Formula-level reference for weighted machine-learning calibration and barangay-scale Gamma–Poisson simulation.</p></div><aside><strong>Scope warning</strong><p>Scenario projection, not official outbreak declaration. Historical monthly dengue values were interpolated from annual totals.</p></aside></section>

  <nav className="methodology-index" aria-label="Methodology sections"><a href="#ensemble">01 Ensemble</a><a href="#baseline">02 Baseline</a><a href="#spatiotemporal">03 Space + time</a><a href="#bayesian">04 Bayesian engine</a><a href="#alerts">05 Risk rules</a><a href="#provenance">06 Data</a></nav>

  <section className="methodology-section" id="ensemble"><header><span>01</span><div><small>Machine-learning layer</small><h2>Weighted ensemble calibration</h2></div></header><p className="section-intro">Four municipality-level model predictions are combined using nonnegative weights constrained to sum to one. This artifact calibrates historical municipality profiles. It is not rerun inside each future barangay simulation.</p><div className="formula-card"><span>Ensemble prediction</span><code>ŷ<sub>ens</sub> = 0.4676ŷ<sub>MLR</sub> + 0.1601ŷ<sub>SARIMAX</sub> + 0.1547ŷ<sub>LSTM</sub> + 0.2176ŷ<sub>XGB</sub></code><small>Final prediction floor: ŷ<sub>final</sub> = max(0, ŷ<sub>ens</sub>)</small></div><div className="methodology-grid"><article><h3>Learned weights</h3>{weights.map(([name,value])=><div className="weight" key={name}><span>{name}</span><i style={{width:value}}/><strong>{value}</strong></div>)}</article><article><h3>Untouched test set</h3><div className="metric-grid">{metrics.map(([name,value])=><div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div><small>January 2024–December 2025. Packaged test table covers 216 municipality-month observations.</small></article></div><div className="formula-card compact"><span>Municipality calibration factor</span><code>c<sub>m</sub> = clip(Σ actual<sub>m</sub> / Σ ensemble<sub>m</sub>, 0.70, 1.30)</code></div></section>

  <section className="methodology-section" id="baseline"><header><span>02</span><div><small>Historical signal</small><h2>Seasonality, trend, and threshold</h2></div></header><div className="methodology-grid three"><article><h3>Monthly climatology</h3><code>C<sub>i,m</sub> = max(c<sub>municipality(i)</sub> · mean(Y<sub>i,t</sub> | month(t)=m, t≥2021), 0)</code><p>Missing calendar months are interpolated, then backward- and forward-filled.</p></article><article><h3>Capped annual growth</h3><code>g<sub>i</sub> = clip(exp(slope(log(1 + annual cases))) − 1, −0.03, 0.03)</code><p>At least four annual totals required; otherwise growth is zero.</p></article><article><h3>Outbreak threshold</h3><code>T<sub>i</sub> = max(1, ceil(max(Q<sub>0.90</sub>, mean + 1.5 · SD)))</code><p>Barangay-specific threshold derived from historical estimated cases.</p></article></div><div className="formula-card"><span>Long-range monthly baseline</span><code>B<sub>i,s</sub> = max(C<sub>i,month(s)</sub> · (1 + g<sub>i</sub>)<sup>h·exp(−h/10)</sup>, 10<sup>−5</sup>)</code><small>h is forecast horizon in years. Damping limits compounding over long horizons.</small></div></section>

  <section className="methodology-section" id="spatiotemporal"><header><span>03</span><div><small>Dependency structure</small><h2>Temporal memory and spatial pressure</h2></div></header><div className="formula-card"><span>Temporal memory</span><code>M = 0.50Y<sub>t−1</sub> + 0.20 mean(Y<sub>t−1:t−3</sub>) + 0.15 mean(Y<sub>t−1:t−6</sub>) + 0.15 mean(Y<sub>t−1:t−12</sub>)</code><small>Temporal blend: A<sup>(t)</sup> = 0.75B + 0.25M</small></div><div className="methodology-grid"><article><h3>Spatial lag</h3><code>S<sub>i</sub> = Σ<sub>j</sub> w<sub>ij</sub> μ̂<sub>j,t−1</sub></code><p>Weights are row-standardized. Polygon-touching neighbors receive raw weight 1; fallback links use inverse distance.</p></article><article><h3>Neighbor boost</h3><code>A<sup>(n)</sup> = (0.82A<sup>(t)</sup> + 0.18S) · (1 + 0.10H)</code><p>H is weighted share of neighbors previously classified HIGH or CRITICAL.</p></article></div><p className="methodology-note">Latest generated graph: 199 barangays, 580 undirected edges, one connected component.</p></section>

  <section className="methodology-section" id="bayesian"><header><span>04</span><div><small>Uncertainty engine</small><h2>Gamma–Poisson posterior prediction</h2></div></header><div className="flow"><article><b>1</b><span>Prior uncertainty</span><code>V = max((CV · μ)², 0.20μ + 0.02)</code></article><article><b>2</b><span>Gamma parameters</span><code>α = μ²/V<br/>β = μ/V</code></article><article><b>3</b><span>Observation update</span><code>α′ = α + y<br/>β′ = β + exposure</code></article><article><b>4</b><span>250 simulations</span><code>λ ∼ Gamma(α′, rate β′)<br/>Y ∼ Poisson(λ)</code></article></div><div className="formula-card"><span>Posterior predictive outputs</span><code>μ̂ = mean(Y<sup>(1…250)</sup>) &nbsp; · &nbsp; 95% interval = [Q<sub>0.025</sub>, Q<sub>0.975</sub>]</code><small>Random seed 42. Horizon uncertainty grows from CV 0.42 by 0.018 per forecast year, capped at 0.95.</small></div></section>

  <section className="methodology-section" id="alerts"><header><span>05</span><div><small>Decision layer</small><h2>Probability and alert rules</h2></div></header><div className="formula-card"><span>Outbreak probability</span><code>p<sub>i,s</sub> = (1 / 250) Σ 1[Y<sub>i,s</sub><sup>(r)</sup> ≥ T<sub>i</sub>]</code><small>Probability resolution is 1/250 = 0.004.</small></div><div className="alert-scale"><span>LOW<br/><b>&lt; 0.30</b></span><span>MODERATE<br/><b>0.30–0.59</b></span><span>HIGH<br/><b>0.60–0.79</b></span><span>CRITICAL<br/><b>≥ 0.80</b></span></div><p className="methodology-note">Individual outbreak rule activates when probability is at least 0.75 or projected mean reaches barangay threshold. Spatio-temporal alerts also consider persistence and connected high-risk neighbors.</p></section>

  <section className="methodology-section" id="provenance"><header><span>06</span><div><small>Evidence boundaries</small><h2>Data provenance and limitations</h2></div></header><div className="methodology-grid three"><article><h3>Historical dengue</h3><p>Annual municipality totals were smoothed into monthly values and allocated to barangays by annual population share.</p><strong className="status">SYNTHETIC_INTERPOLATED</strong></article><article><h3>Spatial data</h3><p>Real barangay boundaries provide topology, centroids, distances, and adjacency for South Cotabato.</p></article><article><h3>Weather context</h3><p>Open-Meteo observations and 16-day forecasts are shown separately. They do not alter Bayesian outbreak probability until validated through backtesting.</p></article></div><div className="provenance-table"><div><span>Forecast scope</span><strong>Jan 2026–Dec 2050</strong></div><div><span>Spatial scope</span><strong>199 barangays · 11 localities</strong></div><div><span>Simulation draws</span><strong>250 per barangay-month</strong></div><div><span>Validated observations packaged</span><strong>None in latest run</strong></div></div></section>

  <footer><strong>ORACLIS Methodology Reference</strong><span>Implementation-grounded documentation · scenario intelligence, not diagnosis</span><a href="#/">Return to dashboard →</a></footer>
</main>}
